### ISSUE TITLE
在转换标题语法时, 如行内以空格开头, 则光标会错位挪到下一行

### ISSUE THREAD

**Issue by XMB-7** [obsidian-canzi/Enhanced-editing#11]
![图片](https://user-images.githubusercontent.com/65625632/161376634-1899cd3d-f689-4bde-9ff7-86d2471dc88e.png)
如果将之设为1级标题,
目前行为:
![图片](https://user-images.githubusercontent.com/65625632/161376707-a24c86c3-0b59-4d88-a4ee-cbc99e3d430a.png)
预期行为:
![图片](https://user-images.githubusercontent.com/65625632/161376685-46716e0e-37ee-4ed0-b71d-1410cf214f46.png)

更异常的是, 行内只有空格的时候, 将之设为标题, 光标会比预期行为下挪三行
![图片](https://user-images.githubusercontent.com/65625632/161376723-900ad076-9c84-444d-b8f5-d4d8a4dfc6c8.png)
![图片](https://user-images.githubusercontent.com/65625632/161376772-c5b54ebd-634a-41e3-9121-0d98b9cc7127.png)

**Comment by obsidian-canzi** [comment]
标题前加空格，我偶尔也这样用，但算法中确实没考虑这种情况。
我调试一下。

**Comment by obsidian-canzi** [comment]
已修复，感谢建议。
