### ISSUE TITLE
每次插件更新, 都会将用户自设的快捷键重置成插件默认状态.

### ISSUE THREAD

**Issue by XMB-7** [obsidian-canzi/Enhanced-editing#13]
好不容易逐渐磨合调整出了一套适合自己使用的快捷键, 但升级一次就要全部重新设置一遍, 随着插件命令越来越多, 这点是很折磨人的.
而且难免让人不想主动升级, 感觉现有功能够用就行, 没必要多费事.
不知道这是不是所有未上架第三方插件商城的插件的通病, 能否尝试解决.

**Comment by obsidian-canzi** [comment]
因为带着data.json数据文件一并更新了，相当于覆盖了参数设置（含5项颜色值）。不过快捷键应该是不会覆盖，除非是改过插件ID。

**Comment by XMB-7** [comment]
> 不过快捷键应该是不会覆盖，除非是改过插件ID。

你可以再找人试试, 之前没上github我就手动更新过一次, 那次快捷键就重置了. 然后这次我用brat管理内测插件自动更新的, 然后又重置了. 感觉很迷, 按理来说不应该才对, 更新其它公测内测插件都没遇到过这种情况.

难道是因为我之前手动更新的那版没删除吗, 但两个插件文件夹名都不一样了, 应该没有影响才对. (前者叫enhancd-editing后者叫ZH增强编辑)
![图片](https://user-images.githubusercontent.com/65625632/161721649-bf243675-6fd3-4a84-84fe-976429fd5084.png)

**Comment by XMB-7** [comment]
刚刚通过brat更新了0.4.8, 有没再出现自设快捷键重置的问题, 这个issue我先关了.
