### ISSUE TITLE
功能请求：能否考虑重新加回【游标移至文首】、【游标移至文末】功能？

### ISSUE THREAD

**Issue by tyf2018** [obsidian-canzi/Enhanced-editing#14]
如题，能否考虑重新加回【游标移至文首】、【游标移至文末】功能？就是将光标移动至首行行首、尾行行尾，这两个功能我经常用到，0.4.6版本貌似删掉了，谢谢。

**Comment by obsidian-canzi** [comment]
谢谢建议。已恢复【游标移至文首】【游标移至文末】两项功能
