### ISSUE TITLE
FR: 常驻显示格式刷已开启的提示, 直至格式刷关闭.

### ISSUE THREAD

**Issue by XMB-7** [obsidian-canzi/Enhanced-editing#15]
亦即常驻显示此提示, 直至用户将相应格式刷功能关闭, 或主动点击提示文本框将之关闭. 没有醒目的常驻提示, 较容易忘记已开启格式刷, 比如分心看了会手机, 再回到文档编辑, 八成就给忘了. 
![图片](https://user-images.githubusercontent.com/65625632/162032642-64d85650-439f-4064-a2d6-380bc6ee4ae2.png)

另外, 打开斜体格式刷和粗体格式刷之时, 相应提示浮窗的显示异常, 直接一闪而过, 不会短暂停留. 其余格式刷正常.
再者就是显示文字可以调整一下, `「下划线」刷`补充修改成`「下划线」格式刷`, 其余各格式刷同理.

**Comment by obsidian-canzi** [comment]
谢谢建议。最近在做几种新的格式刷，一直在处理这个效果（打开格式刷就一直显示提示，直到关闭时才让提示消失），可惜代码水平有限，总不完美。后期会把所有格式刷都这样处理，或做成其它样式的提醒。

**Comment by XMB-7** [comment]
这个可以暂时先按插件提示版本更新信息那样处理. 开启格式刷, 用户只要不点浮窗, 浮窗就不消失, 这个似乎不需要额外写多少代码.
以后或许可以做成魔改cmenu那种浮窗跟随鼠标的效果, 但我个人觉得其实有前一种就够用了.

**Comment by obsidian-canzi** [comment]
已经实现了。

**Comment by XMB-7** [comment]
很强. 
有一点小建议是不必显示颜色, 反正绝大多数用户看16进制数, 脑海里也反映不出这到底是啥颜色, 倒是可以把相应颜色用浮窗表示出来, 亦即直接把提示浮窗的颜色就设为格式刷的颜色. 当然这个优先度就很低了, 有没有都行.

**Comment by XMB-7** [comment]
发现一个相关的小bug.
![图片](https://user-images.githubusercontent.com/65625632/163720608-cd7bec94-665c-4bc7-9378-aa9b0770c11e.png)
然后这个issue酌情可以关了, 如果没有其它价值的话.
