### ISSUE TITLE
功能请求: 新增打开快捷键设置面板的菜单选项

### ISSUE THREAD

**Issue by XMB-7** [obsidian-canzi/Enhanced-editing#17]
![图片](https://user-images.githubusercontent.com/65625632/163754094-403d7d5f-aaa6-4b60-aa10-7a7a4279558f.png)

执行选项，打开ob快捷键设置面板，并且自动输入增强编辑。
![图片](https://user-images.githubusercontent.com/65625632/163754255-907a3685-f9f3-4aec-a3e6-642dbde0e8c1.png)

**Comment by obsidian-canzi** [comment]
谢谢，很好的建议。而且细节处理的到位。
已经实现。
如有其它功能点需要完善或补充，欢迎留言。
