### ISSUE TITLE
当行首存在空格或制表符时，一键设置标题的命令会失效

### ISSUE THREAD

**Issue by tyf2018** [obsidian-canzi/Enhanced-editing#27]
当行首存在空格或制表符时，一键设置标题的命令会失效，变成如下格式：空格/制表符## 文字  
针对这种情况，一键设置标题时，能否自动删掉行首的空格或制表符？
谢谢

**Comment by obsidian-canzi** [comment]
感谢反馈问题，已修复，不日更新。

**Comment by tyf2018** [comment]
更新后问题已解决，赞
