### ISSUE TITLE
切换笔记时右边软件通知栏不断跳出 『欢迎使用』

### ISSUE THREAD

**Issue by PlanetesDDH** [obsidian-canzi/Enhanced-editing#4]
![image](https://user-images.githubusercontent.com/45725850/160263823-91f42ecb-aef4-484d-913f-8af46726e53c.png)

**Comment by obsidian-canzi** [comment]
这是一个版本更新的提示窗口，但因为data.json文件没有正确存储造成不会自动消除，已在0.4.7版本中解决。
