### ISSUE TITLE
【功能请求】一键荧光变涂黑，一键涂黑变荧光

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [obsidian-canzi/Enhanced-editing#41]
蚕子你好，

我想提出一个挖空的需求

因为obsidian to anki中高亮可以制卡为挖空，所以通常我回使用荧光笔
格式为
==obsidian==
同时在blue主题中涂黑的格式可以为
==~~obsidian~~==
基于此我想提出一个需求在增强编辑中增加
一键荧光变涂黑（obsidian阅读使用）
一键涂黑变荧光（obsidian制卡使用）

我不会编程，自己用查找替换是不行的（因为荧光两边都是==一样的），所以麻烦大神了

**Comment by shoudeyunkaijianyueming** [comment]
<img width="682" alt="image" src="https://user-images.githubusercontent.com/71814666/194451126-945a4031-b493-445f-af01-19052ed411df.png">

**Comment by obsidian-canzi** [comment]
你好。md语法的默认高亮是用==高亮==样式吧。要想保证 =~效果~= 生效的话，得使用css吧。目前增强编辑插件已经脱离css效果了，防止对原主题或其它css造成冲突。

**Comment by shoudeyunkaijianyueming** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1801211637
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    好的谢谢蚕子
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年10月7日 18:14
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [obsidian-canzi/Enhanced-editing] 【功能请求】一键荧光变涂黑，一键涂黑变荧光 (Issue #41)
        
      
    
  
  

你好。md语法的默认高亮是用==高亮==样式吧。要想保证 =效果= 生效的话，得使用css吧。目前增强编辑插件已经脱离css效果了，防止对原主题或其它css造成冲突。



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
