### ISSUE TITLE
[bug] 编辑模式下对注释的显示异常

### ISSUE THREAD

**Issue by XMB-7** [obsidian-canzi/Enhanced-editing#49]
偶然发现, 插件似乎对注释(`%%...%%`)的显示异常.

关闭插件, 正常显示效果如下.
![image](https://user-images.githubusercontent.com/65625632/202235421-ec64b097-07c5-4b6f-a22f-8a4a5fa47b71.png)

开启插件, 异常显示效果如下. 右侧出现了浮窗一样的东西容纳注释内容, 而且还超出了屏幕.
![image](https://user-images.githubusercontent.com/65625632/202235575-30f9975a-80fa-4e80-9841-9fefc062b304.png)

**Comment by obsidian-canzi** [comment]
更新一下版本。或给插件文件夹里的css文件删除

**Comment by XMB-7** [comment]
已是最新版, 把styles.css删了, 就好了. 感谢.
