### ISSUE TITLE
[fr] 纠正命令错误说明

### ISSUE THREAD

**Issue by XMB-7** [obsidian-canzi/Enhanced-editing#51]
偶然发现, 这俩命令实际执行的是游标移至段首/段尾, 而非行首行尾, 亦即可以跨行, 建议进行修正.
![image](https://user-images.githubusercontent.com/65625632/205502018-98cba3ee-0eb2-452b-b996-0c75ad4e052f.png)

**Comment by obsidian-canzi** [comment]
欢迎QQ交流，312815311.
我理解的ob笔记是一行就是一段。如果是视觉上的一行首尾跳转，可用home和end键来执行。
