### ISSUE TITLE
【功能请求】要是作者能够在转换内部链接（全局）中追加别名（aliases）就好了

### ISSUE THREAD

**Issue by Ameryou** [obsidian-canzi/Enhanced-editing#55]
看见国外有人用python脚本做了，但我自己没学过。运行之后又是TypeError看不懂好难受。又很馋这个功能（磕头）
https://github.com/vince8x/obs_batch-linkr/blob/master/obs-batch-linkr.py
https://github.com/perkinsben/obs_tools/blob/master/forward_linker/obs-linkr.py

**Comment by Ameryou** [comment]
才发现作者大大更新了，不处理yaml和标签内容了，那没事了。
不过发现在使用全局转化内链的时候，并不会把一个字的链接变成内链，比如我笔记里面一个字的：[[頸]][[腿]][[脣]之类的。
另外重复的内容也只会给第一次出现的词语加上[[]]，比如只会给第一个出现的うなだれ加上[[]]，后面再出现就没加[[]]了，是有什么考量在里面吗。

**Comment by obsidian-canzi** [comment]
你好，转换内链时规避单字名称的标题，当初主要是考虑英文单字符，因为[[i]]的转换会让原文惨不忍睹。如果是处理非英文或单词类语言的话，比如中文单字符名称具备独特意义的话，是可以考虑调整的。就是代码里一处>1的修改为>0，你自已也可以尝试。
重复内容只转换第1处词语，是参考wiki的效果，防止某些人物生平类内容中重复出现[[某某]]...[[某某]]...的情况。原则是轻松去除[]符号，慎重设置内链。
