### ISSUE TITLE
pdf ocr之后的整段文字，是一行一行的

### ISSUE THREAD

**Issue by Juan-hwt** [obsidian-canzi/Enhanced-editing#71]
探索建立差异化监管指标体系。完善农商银行的监管
分类标准，建立差异化监管体系，研究借鉴城商行监管标
准，推动城区农商银行加快商业化、市场化发展，充分发
挥指标对城区农商银行高质量发展的指引作用。优化分层
监测预警指标体系，在不良率、大额贷款占比、房地产贷
款占比等方面，给予城区农商银行更宽松的政策。

如何在ob中，让它快速成为一个段落？？

**Comment by shiquda** [comment]
选中文本，然后使用这个功能
![image](https://github.com/obsidian-canzi/Enhanced-editing/assets/104683621/b3c396fb-7457-48c0-b64d-f387522b0986)

**Comment by obsidian-canzi** [comment]
感谢回复。我在0.6.2版本又增加了一个【修复外来文本】的合并功能，欢迎测试。

**Comment by Juan-hwt** [comment]
> 选中文本，然后使用这个功能 ![image](https://user-images.githubusercontent.com/104683621/272268058-b3c396fb-7457-48c0-b64d-f387522b0986.png)

实测有效，谢谢
