### ISSUE TITLE
Alt+;快捷键Callout替换相关问题

### ISSUE THREAD

**Issue by PlanetesDDH** [obsidian-canzi/Enhanced-editing#8]
尝试了一下, 输入『成功+若干内容后』使用快捷键不会触发替换, 但是『笔记+若干内容后』会导致改行内容被Callout覆盖, 
个人感觉这是个问题, 因为可能会误触快捷键等问题. (其他关键字未测试)

**Comment by obsidian-canzi** [comment]
使用方法不对。只输入【成功】再按快捷键，转换为callout语法后再输入标题，因为光标会自动定位。

**Comment by obsidian-canzi** [comment]
试一下新版本吧，我更新后补充了【类型 对齐方式 折叠】缩录的方案。
