### ISSUE TITLE
功能请求: 调整转换链接功能

### ISSUE THREAD

**Issue by XMB-7** [obsidian-canzi/Enhanced-editing#9]
1.关于使用alt+z在选文两端添加或去除`[[ ]]`符号
Obsidian本身对在选文两端添加`[[ ]]`符号这件事, 已经支持得很好了(直接按两下`[[`即可), 但同时却没有支持便捷删除`[[ ]]`. 
因此建议扩充对删除`[[ ]]`的功能支持, 除了划选以外, 直接允许按键删除包裹光标的最近一层`[[ ]]`. 比如对于`[[xxx]]`, 直接把光标点进方括号, 按一下快捷键即可删除`[[ ]]`. 类似于转换无语法文本(ctrl+alt+z)这一功能的实现方式.
至于当前的划选删除操作模式, 也要同时保留. 如此一来, 以后单次删除就不用划选了, 操作进一步便捷了, 而需要批量删除的时候再进行划选. 

2.关于使用alt+q添加[[|选文]]
这个功能目前在表格里使用是有问题的, 因为并没有对|进行转义.
比如这样书写,
![图片](https://user-images.githubusercontent.com/65625632/161318415-0ee88d54-5420-4fab-8a31-4b7e0420f152.png)
实际展示出来是这样的,
![图片](https://user-images.githubusercontent.com/65625632/161318506-a488a91b-63db-4e92-bf2e-769b225365ff.png)
我必须手动补一个转义符, 然后才能正常显示. 如果同一时间需要手补多个, 特别折磨.
![图片](https://user-images.githubusercontent.com/65625632/161318613-147d3ee5-ea18-4de8-ac69-d27be6ff1f06.png)
![图片](https://user-images.githubusercontent.com/65625632/161320564-03905db7-7797-4ec0-8969-8e2a1c344406.png)
因此建议, 先识别一下选文是否被`|加若干空格`包裹, 如果是, 就表明在表格里调用的该功能, 那就自动给`|`多加一个转义符. 
或者退而求其次, 额外多弄出一条指令与配套的快捷键, 专门让用户在表格中使用该功能.

3.修改功能相关文本说明
![图片](https://user-images.githubusercontent.com/65625632/161320686-06ae602a-fdc8-4961-829b-3458642d9d37.png)
第一个改为"支持批量转换用换行符分隔的被选中的多行文本或用顿号分隔的被选中的多个字符串"
第二个改为"选文之中禁止含有..."

**Comment by obsidian-canzi** [comment]
![图片](https://user-images.githubusercontent.com/16410542/161379231-a634fbe3-43b2-4537-a3ab-91a11a91a4bd.png)
感谢你的建议，我也喜欢处理这些细节问题，更显人性化。
可惜在表格中测试补加转义符号后，选择笔记名列表后会自动去除转义及|以后的内容。
还是希望能QQ详谈，方便沟通与测试。

**Comment by obsidian-canzi** [comment]
第1条建议非常好，已用模拟划选的方式实现，请回头测试。
第3条建议非常细致，已重新整理措辞。

**Comment by XMB-7** [comment]
> 还是希望能QQ详谈，方便沟通与测试。

好的. 最近疫情封城, 在家没事捋着插件文档把每个功能都试一下, 发现功能确实丰富, 但有些也确实有优化的空间. 等我大致把功能都试一遍, 然后整理一下各种反馈, QQ联系. 
用GitHub主要是发现一个点就可以提一个issue, 随时可以反馈, 时间上比较自由.
